### PR TITLE
Added opus codec const

### PR DESCRIPTION
**Pull request by Nik99**
Added opus codec const

### CODE REVIEW

**Comment by par0noid** [comment]
I knew that there're codecs for opus but they're not documented, that's why i did not add them to the class. But ... let's do it 👍

**Comment by Nik99** [comment]
Actually by printing out value for opus codecs there are 4 and 5 so.. i think it should be fine
Never noticed that they're not documented, try reporting it to Teamspeak Devs

**Comment by par0noid** [comment]
Yea, this is not documented in the serverquerydoc. I saw it in other librarys that they have 4 and 5, but i did not want to give the impression I did a copy&paste from other librarys

**Comment by Nik99** [comment]
This library is much much simple and better of other libraries.
No reason to copy&paste :) :+1:

**Comment by Nik99** [comment]
Ooops, i didn't noticed that i forgot to update composer.json version
@par0noid can you do it ? ahah

**Comment by par0noid** [comment]
Sure :)

**Pull request merged**
