### PR TITLE
Added Read Chat Message & more

### PR DESCRIPTION
**Pull request by toxiicdev**
[+] Added readChatMessage (you can now get messages written in server, channel, private) - This is a blocking function that you must use in a while (without a sleep to receive all packets - will not waste your CPU due it waits next message - always check for return data success)
[+] Added getQueryClid - returns server query client id for any purpose
[+] Added loadQueryData (after select server) - loads query clid and nickname (example: serverquery from 127.0.0.1:1337)
[+] Added serverNotifyUnregister - Unregister any server notify (required for readChatMessage)

### CODE REVIEW

**Comment by par0noid** [comment]
The ts3admin.clas is not designed to be used as a daemon. I'm not sure if it is a good idea to merge this to the class.

**Comment by Nik99** [comment]
@par0noid, why not ?

Users are not forced to use it, it's only a plus functionality.

**Comment by toxiicdev** [comment]
@par0noid Those are additional features that may involve people to use the class

**Comment by par0noid** [comment]
Okay, merged it. But I think that functions like serverNotifyUnregister need a return array with success, and error

**Pull request merged**
